name: "Load Artifact"
description: "Downloads and unzips a saved artifact using the temp directory"
inputs:
  name:
    description: 'The artifact filename'
    required: true
    default: 'deploy-artifact'
  destination:
    description: 'Where to unzip the artifact into'
    required: true
    default: ${{ github.workspace }}
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.name }}
        path: ${{ runner.temp }}
    - run: tar -xf ${{ runner.temp }}/${{ inputs.name }}.tar -C ${{ inputs.destination }}
      shell: bash
