name: Pre Build Pantheon project
description: Pre Build Pantheon site
runs:
  using: "composite"
  steps:
    - name: Ensure branch name is less than 12 characters
      run: |
        BRANCH_NAME=${{ github.ref_name }}
        if [[ '${{ github.ref }}' == 'refs/heads/master' ]]; then
          echo "BRANCH_VALID=true" >> $GITHUB_ENV
        elif [[ ${BRANCH_NAME} == md-* && ${#BRANCH_NAME} -le 11 ]]; then
          echo "BRANCH_VALID=true" >> $GITHUB_ENV
        else
          echo "BRANCH_VALID=false" >> $GITHUB_ENV

    - name: Stop if Branch is Invalid
      if: env.BRANCH_VALID == 'false'
      run: |
        echo "Branch name cannot contains more than 11 characters. Stopping workflow."
        exit 1