name: Post Deploy Pantheon project
description: Post Deploy Pantheon site
inputs:
  PANTHEON_SITE:
    description: 'The Pantheon site name.'
    required: true
    type: string
  TERMINUS_TOKEN:
    description: 'Token to use with the Terminus cli.'
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Set Environment Variable
      id: setenv
      run: echo "PANTHEON_ENV=$(if [ '${{ github.ref }}' == 'refs/heads/master' ]; then echo 'dev'; else echo '${{ github.ref_name }}'; fi)" >> $GITHUB_ENV
      shell: bash

    - name: Check Environment
      if: env.PANTHEON_ENV == ''
      run: |
        echo "Stopping workflow as PANTHEON_ENV is set to 'other'."
        exit 1
      shell: bash

    - name: Install Terminus
      uses: pantheon-systems/terminus-github-actions@main
      with:
        pantheon-machine-token: ${{ inputs.TERMINUS_TOKEN }}

    - name: Terminus Drush Updates
      run: |
        terminus env:wake ${{ inputs.PANTHEON_SITE }}.${{ env.PANTHEON_ENV }}
        terminus env:code-rebuild ${{ inputs.PANTHEON_SITE }}.${{ env.PANTHEON_ENV }}
        terminus drush ${{ inputs.PANTHEON_SITE }}.${{ env.PANTHEON_ENV }} -- deploy
        terminus env:clear-cache ${{ inputs.PANTHEON_SITE }}.${{ env.PANTHEON_ENV }}
      shell: bash