name: Deploy Repository
on:
  workflow_call:
jobs:
  pre_build:
    uses: elevatedthird/actions/.github/workflows/pre_build.yml@main
  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    env:
      DESTINATION_REPOSITORY_BRANCH: ${{ github.ref_name }}
      TAG: ${{ github.ref_name }}-${{ github.run_number }}
      TAG_MESSAGE: Github Actions build ${{ github.run_number }}
      USER_EMAIL: github-actions@github.com
      USER_NAME: github-actions
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install SSH key
        uses: ./gh/.github/workflows/ssh-agent
        with:
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ env.REMOTE_GIT_HOST }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
      - name: Push to Remote
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git remote add prod ${{ inputs.DESTINATION_REPOSITORY }}
          git push prod $DESTINATION_REPOSITORY_BRANCH --force
          git tag -a "${TAG}" -m "${TAG_MESSAGE}"
          git push prod $TAG
  post_deploy:
    uses: elevatedthird/actions/.github/workflows/post_deploy.yml@main
    secrets: inherit
