name: Post Deploy Project
on:
  workflow_call:
jobs:
  pre_build:
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.1.2
        with:
          path: .env
          export-variables: true
          export-variables-prefix: DOTENV_
          keys-case: bypass

      - name: Install SSH key
        uses: elevatedthird/actions/.github/actions/ssh-agent@main
        with:
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_url: ${{ env.DOTENV_DESTINATION_REPOSITORY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: Pantheon Post Deploy
        if: ${{ env.DOTENV_PLATFORM }} == 'pantheon'
        uses: elevatedthird/actions/.github/workflows/pantheon/post_deploy@main
